(self.AMP=self.AMP||[]).push({n:"amp-sticky-ad",v:"1901021931380",f:(function(AMP,_){
var d,e="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},h;if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var k;a:{var m={a:!0},n={};try{n.__proto__=m;k=n.a;break a}catch(a){}k=!1}h=k?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var p=h;self.log=self.log||{user:null,dev:null,userForEmbed:null};var q=self.log;function r(){if(!q.user)throw Error("failed to call initLogConstructor");return q.user}function t(a){r().assert(a,"amp-sticky-ad must have a single amp-ad child",void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function u(){var a,b=Object.create(null);a&&Object.assign(b,a);return b};function v(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var w,x="Webkit webkit Moz moz ms O o".split(" ");function y(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function z(){var a,b;this.promise=new Promise(function(c,I){a=c;b=I});this.resolve=a;this.reject=b};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function A(a){v(a.tagName,"AMP-");if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new z;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};function B(a){a=AMP.BaseElement.call(this,a)||this;a.m=a.getVsync();a.h=null;a.c=null;a.l=!1;a.j=null;a.w=!1;a.o=null;return a}var E=AMP.BaseElement;B.prototype=e(E.prototype);B.prototype.constructor=B;if(p)p(B,E);else for(var F in E)if("prototype"!=F)if(Object.defineProperties){var G=Object.getOwnPropertyDescriptor(E,F);G&&Object.defineProperty(B,F,G)}else B[F]=E[F];B.C=E.prototype;d=B.prototype;
d.buildCallback=function(){var a=this;this.c=this.getViewport();this.element.classList.add("i-amphtml-sticky-ad-layout");var b=this.getRealChildren();t(1==b.length&&"AMP-AD"==b[0].tagName);this.h=b[0];this.setAsOwner(this.h);this.o=A(this.h).then(function(a){return a.whenBuilt()}).then(function(){return a.mutateElement(function(){y(a.element,!0)})});var c=this.win.document.createElement("amp-sticky-ad-top-padding");c.classList.add("amp-sticky-ad-top-padding");this.element.insertBefore(c,this.h);this.win.setTimeout(function(){a.j=
a.c.onScroll(function(){1<a.c.getScrollTop()&&H(a)})})};d.layoutCallback=function(){if(this.l){y(this.element,!0);var a=this.element.offsetHeight;this.c.updatePaddingBottom(a);this.updateInViewport(this.h,!0);this.scheduleLayout(this.h)}return Promise.resolve()};d.isAlwaysFixed=function(){return!0};d.unlayoutCallback=function(){this.c.updatePaddingBottom(0);return!0};d.detachedCallback=function(){J(this)};d.collapsedCallback=function(){var a=this;this.w=!0;this.l=!1;y(this.element,!1);this.m.mutate(function(){a.c.updatePaddingBottom(0)})};
function J(a){a.j&&(a.j(),a.j=null)}function H(a){J(a);a.o.then(function(){a.mutateElement(function(){a.w||(a.l=!0,K(a),a.c.addToFixedLayer(a.element,!0).then(function(){return L(a)}))})})}function L(a){A(a.h).then(function(b){b.whenBuilt().then(a.A.bind(a))})}
d.A=function(){var a=this,b=this.h;this.updateInViewport(b,!0);this.scheduleLayout(b);var c=b.signals();return Promise.race([c.whenSignal("render-start"),c.whenSignal("load-end")]).then(function(){var b;return a.measureElement(function(){b=(a.win.getComputedStyle(a.element)||u()).backgroundColor}).then(function(){return a.m.mutatePromise(function(){a.element.setAttribute("visible","");a.c.updatePaddingBottom(a.element.offsetHeight);var c=b,C=c.replace(/\(([^,]+),([^,]+),([^,)]+),[^)]+\)/g,"($1,$2,$3, 1)");
if(c!=C){r().warn("AMP-STICKY-AD","Do not allow container to be semitransparent");c=a.element;var g=c.style;if(v("background-color","--"))g="background-color";else{w||(w=u());var l=w["background-color"];if(!l){l="background-color";if(void 0===g["background-color"]){var f;b:{for(f=0;f<x.length;f++){var D=x[f]+"Background-color";if(void 0!==g[D]){f=D;break b}}f=""}void 0!==g[f]&&(l=f)}w["background-color"]=l}g=l}g&&(c.style[g]=C)}})})})};
function K(a){var b=a.win.document.createElement("button");b.classList.add("amp-sticky-ad-close-button");b.setAttribute("aria-label",a.element.getAttribute("data-close-button-aria-label")||"Close this ad");var c=a.B.bind(a);b.addEventListener("click",c);a.element.appendChild(b)}d.B=function(){var a=this;this.m.mutate(function(){a.l=!1;a.scheduleUnlayout(a.h);a.c.removeFromFixedLayer(a.element);var b=a.element;b.parentElement&&b.parentElement.removeChild(b);a.c.updatePaddingBottom(0)})};
(function(a){a.registerElement("amp-sticky-ad",B,"amp-sticky-ad{position:fixed!important;text-align:center;bottom:0!important;left:0;width:100%!important;z-index:11;max-height:100px!important;box-sizing:border-box;opacity:1!important;background-image:none!important;background-color:#fff;box-shadow:0 0 5px 0 rgba(0,0,0,0.2)!important;margin-bottom:0!important}amp-sticky-ad-top-padding{display:block;width:100%!important;background:#fff;height:4px;max-height:5px!important;z-index:12}.i-amphtml-sticky-ad-layout{display:-webkit-box;display:-ms-flexbox;display:flex;visibility:hidden!important;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:center;-ms-flex-pack:center;justify-content:center;overflow:visible!important;-webkit-transform:translateZ(0)!important;transform:translateZ(0)!important}amp-sticky-ad[visible]{visibility:visible!important}.i-amphtml-sticky-ad-layout>amp-ad{display:block}.amp-sticky-ad-close-button{position:absolute;visibility:hidden;width:32px;cursor:pointer;height:28px;top:-24px;background-image:url(\"data:image/svg+xml;charset=utf-8,%3Csvg width='13' height='13' viewBox='341 8 13 13' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath fill='%234F4F4F' d='M354 9.31L352.69 8l-5.19 5.19L342.31 8 341 9.31l5.19 5.19-5.19 5.19 1.31 1.31 5.19-5.19 5.19 5.19 1.31-1.31-5.19-5.19z' fill-rule='evenodd'/%3E%3C/svg%3E\");background-size:13px 13px;background-position:9px;background-color:#fff;background-repeat:no-repeat;box-shadow:0 -1px 1px 0 rgba(0,0,0,0.2);border:none;border-radius:12px 0 0 0}amp-sticky-ad[visible]>.amp-sticky-ad-close-button{visibility:visible}.amp-sticky-ad-close-button:before{position:absolute;content:\"\";top:-20px;right:0;left:-20px;bottom:0}[dir=rtl] .amp-sticky-ad-close-button{right:auto;left:0;border-top-left-radius:0;border-top-right-radius:12px;background-position:6px}[dir=rtl] .amp-sticky-ad-close-button:before{right:-20px;left:0}\n/*# sourceURL=/extensions/amp-sticky-ad/1.0/amp-sticky-ad.css*/")})(self.AMP);
})});
//# sourceMappingURL=amp-sticky-ad-1.0.js.map
